### PR TITLE
Updates to base python GAE dockerfile

### PR DESCRIPTION
**Pull request by mgenti**
Updated to SDK version 1.9.18
Collapsed RUN statements to minimize the size of the resulting Docker image
Cleaned up after apt
Deleted appengine.zip

### CODE REVIEW

**Comment by lhmatt** [comment]
Cheers buddy. We will be updating the whole repo in the coming months. Let me know if you have any requests.

**Comment by mgenti** [comment]
Can you push an updated version to docker hub?
Thanks!

**Comment by lhmatt** [comment]
'Fraid I won't be in the office until this time next week, but I will do it ASAP. Message again if you haven't heard anything by the end of next week.

**Comment by lhmatt** [comment]
I've pushed the latest versions to docker hub. Only done limited testing so let me know if you experience any issues.

**Pull request merged**
